<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="8" hostname="User-PC" failures="1" tests="2" name="Test(failed)" time="0.094" errors="0" timestamp="2022-06-14T19:39:01 IST">
  <testcase classname="failedtestng.Failedtest2" name="method7" time="0.014"/>
  <testcase classname="failedtestng.FailTest1" name="method2" time="0.006">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at failedtestng.FailTest1.method2(FailTest1.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
  <testcase classname="failedtestng.FailTest1" name="method1" time="0.0">
    <ignored/>
  </testcase> <!-- method1 -->
  <testcase classname="failedtestng.Failedtest2" name="method8" time="0.0">
    <ignored/>
  </testcase> <!-- method8 -->
  <testcase classname="failedtestng.FailTest1" name="method3" time="0.0">
    <ignored/>
  </testcase> <!-- method3 -->
  <testcase classname="failedtestng.FailTest1" name="method5" time="0.0">
    <ignored/>
  </testcase> <!-- method5 -->
  <testcase classname="failedtestng.Failedtest2" name="method10" time="0.0">
    <ignored/>
  </testcase> <!-- method10 -->
  <testcase classname="failedtestng.FailTest1" name="method4" time="0.0">
    <ignored/>
  </testcase> <!-- method4 -->
  <testcase classname="failedtestng.Failedtest2" name="method6" time="0.0">
    <ignored/>
  </testcase> <!-- method6 -->
  <testcase classname="failedtestng.Failedtest2" name="method9" time="0.0">
    <ignored/>
  </testcase> <!-- method9 -->
</testsuite> <!-- Test(failed) -->
